### ISSUE TITLE
"Generate Title" feature moves note to root folder instead of current folder

### ISSUE THREAD

**Issue by khanhtoan529** [nhaouari/obsidian-textgenerator-plugin#125]
**Description:**
When using the "Generate Title" feature, the generated title is correct but the note is moved to the root folder instead of the current folder it should be in. This creates confusion and makes it difficult to organize notes.

**Steps to reproduce:**
1. Create a new note in a specific folder
2. Use the "Generate Title" feature to generate a title for the note
3. Notice that the note is moved to the root folder instead of staying in the current folder

**Expected behavior:**
The note should stay in the current folder when using the "Generate Title" feature. The generated title should be added to the note without affecting its location.

**Actual behavior:**
The note is moved to the root folder instead of staying in the current folder when using the "Generate Title" feature.

**Environment:**
Plugin Version: 0.2.17
Obsidian Version: v1.1.16

Additional information:
This issue makes it difficult to organize notes and locate them easily. It would be great if this issue could be fixed soon.

**Comment by nhaouari** [comment]
Thank you for reporting this issue! 
We are happy to inform you that this bug has been fixed in the latest plugin version, v0.2.18. 

We would greatly appreciate your feedback on the updated version and if you encounter any further issues, please don't hesitate to let us know. Thank you again for your help in improving our plugin!
