### ISSUE TITLE
Bug when max number of tokens is set too high

### ISSUE THREAD

**Issue by j-maffe** [nhaouari/obsidian-textgenerator-plugin#138]
When setting the max number of tokens above around 4050 tokens an error occurs:
```
plugin:obsidian-text…erator-plugin:47759 Error: Request failed, status 400
    at new t (app.js:1:717762)
    at Jw (app.js:1:717954)
    at app.js:1:718631
    at app.js:1:235836
    at Object.next (app.js:1:235941)
    at a (app.js:1:234680)
eval	@	plugin:obsidian-text…erator-plugin:47759
```

**Comment by phillipjohnston** [comment]
Another issue clarified max_tokens in such a way that seems to matter for your use case too (https://github.com/nhaouari/obsidian-textgenerator-plugin/issues/105)

> If the sum of prompt_tokens and max_tokens exceeds the maximum request size, the request will fail before the generation process.

And like that user, I expected this to be the case:

> I was thinking that max_tokens was a limit for any given api call, and that context (prompt_tokens) were subtracted from max_tokens, so that the model would only answer utilizing whatever tokens were left.

So I suspect that you have something enabled, like sending the title as context, which is causing the request to fail right away because you're sending some small amount of context that throws the request over the API limit.

**Comment by j-maffe** [comment]
Oh yeah, it seems like you're correct. When I set the value above 4090 or so it crashes with gpt-3.5. I had the same thoughts as the post you linked. I guess an easy fix is to prevent the user from inputting a number higher than the max context window of the model? Or at least put a warning next to that setting.
Thanks! :D

**Comment by zealotCE** [comment]
The same error.

When I set the maximum token count to over 4100. Regardless of which model is used, an error will occur.
like GPT 3.5 turbo / GPT-4 1106 preview / GPT-4.

![image](https://github.com/nhaouari/obsidian-textgenerator-plugin/assets/26129403/76ab5d40-a43c-47f0-b912-34d59f97ce66)
