### ISSUE TITLE
Typing into '/' box causes options to disappear and not autocomplete

### ISSUE THREAD

**Issue by dep** [nhaouari/obsidian-textgenerator-plugin#257]
After the latest update when I 'typeahead' to find anything in the / box, all the options disappear

![CleanShot_2024-02-05_at_12 24 58](https://github.com/nhaouari/obsidian-textgenerator-plugin/assets/55112925/ff5cf220-6f0f-4f49-9abe-2ee66edc2044)

**Comment by haouarihk** [comment]
it dissapear if it doesn't find a match,

i think your prompts are incorrectly configured,
they need either promptId, name, description or tags to be in the metadata.
![image](https://github.com/nhaouari/obsidian-textgenerator-plugin/assets/57036855/98971a66-354d-43e2-ab15-d3a525731a13)
this function boils down the template into a string which will be searchable,
before the latest update, it was also searching with path in mind, but the search results were not great and the performance was getting a hit because of it, we had to minimize the amount of text being used for searching for each item.

we will roll out a fix for this, by using path only incase of name or promptId not being present.

thanks for reporting this bug

**Comment by dep** [comment]
Thank you for the lead about incorrectly configured prompts.  I added a name to the metadata of each prompt and it's working for me now.

ex:
```
---
name: describe
---

Write a paragraph about the following...

{{tg_selection}}
```
