### ISSUE TITLE
Bug: Chat Anthropic LLM Provider with CORS issue

### ISSUE THREAD

**Issue by ckt1031** [nhaouari/obsidian-textgenerator-plugin#259]
Configuration:

![image](https://github.com/nhaouari/obsidian-textgenerator-plugin/assets/65409152/2828b16d-9469-4795-b25f-7f0b6afb0928)

Error Logs:

![image](https://github.com/nhaouari/obsidian-textgenerator-plugin/assets/65409152/6216e924-c409-4559-be38-53b356a08920)

However, it works by using the old legacy anthropic llm provider.

I guess it is the Anthropic CORS issue, there is currently no way to intercept Langchain HTTP function with native Obsidian request function with CORS bypassing.

I suggest to handle anthropic with custom function, and by the way, the new `/v1/messages` (https://docs.anthropic.com/claude/reference/messages_post) endpoint is available for Claude API, that is akin to OpenAI format instead of weird `\n\nhuman`

**Comment by haouarihk** [comment]
langchain http function is not the only issue,
streaming in obsidian with the request function is not currently possible.

and about your second suggestion,
we will add that soon.
Thanks for reporting this

**Comment by ht55ght55** [comment]
I thought I would just tag this on to this issue as it seems related.

claude-3 not working under chat-anthropic

![image](https://github.com/nhaouari/obsidian-textgenerator-plugin/assets/52102108/daf8f891-a9e7-4096-9986-538137d019c3)

As you can see in the inspector, the endpoint is automatically routed to the legacy endpoint.

When I add the updated `messages` endpoint the old `completions` endpoint is appended to create `https://api.anthropic.com/v1/messages/v1/completions`

![image](https://github.com/nhaouari/obsidian-textgenerator-plugin/assets/52102108/96f4e183-0a8d-41e8-ae8c-43aae1b4a85a)


I've tried to play around with this in the `custom`  LLM provider and this is what I've come up with:


![image](https://github.com/nhaouari/obsidian-textgenerator-plugin/assets/52102108/7147efbd-45a2-4113-aa3b-b9dbad1fd2bb)

![image](https://github.com/nhaouari/obsidian-textgenerator-plugin/assets/52102108/23911ff2-ad8a-42cf-be5c-a56d83617747)

![image](https://github.com/nhaouari/obsidian-textgenerator-plugin/assets/52102108/32308145-358d-44db-b19b-883636b8e87b)


As you can see in the inspector, I've managed to get a response from the api but it won't insert in the note due to some `n.decompose` error.  I can't tell if that is due to my hacky api call or the plugin back end.  

I hope this helps!

ps. great plugin, sir.  I can't thank you enough.  I use it every day.
