### ISSUE TITLE
Whisper for Groq

### ISSUE THREAD

**Issue by kunthawat** [nhaouari/obsidian-textgenerator-plugin#310]
I try to use Whisper for Groq.  When I try to extract text from audio, I got error.  It seem the api key don't send. Please fix this bug.

![image](https://github.com/user-attachments/assets/3e803bb3-9d9e-4777-90cf-5939eac05d3e)

Thanks

**Comment by haouarihk** [comment]
This should be fixed in version 0.7.33-beta
and soon will be in the stable release.
[0.7.33-beta](https://github.com/nhaouari/obsidian-textgenerator-plugin/releases/tag/0.7.33-beta)
[Changes](https://github.com/nhaouari/obsidian-textgenerator-plugin/commit/64b80ec561110c29058d09958285394affe90c5e)
thanks for reporting the bug
