### ISSUE TITLE
any chance of adding chatGPT support?

### ISSUE THREAD

**Issue by hannesdelbeke** [nhaouari/obsidian-textgenerator-plugin#59]
hi, wonder if there are any plans of adding chatGPT support?

**Comment by nhaouari** [comment]
Thank you for your question about chatGPT support. At this time, I am unable to add chatGPT support to the plugin because the API is not yet available on OpenAI.

As an alternative, you may be able to use the Custom Frames plugin for Obsidian to incorporate chatGPT functionality into your notes. The Custom Frames plugin allows you to define custom frames that can display dynamic content within your notes. You can find more information about the Custom Frames plugin and how to use it with chatGPT at the following link: [https://www.reddit.com/r/ObsidianMD/comments/zhaxk3/how_to_use_chatgpt_in_obsidian/](https://www.reddit.com/r/ObsidianMD/comments/zhaxk3/how_to_use_chatgpt_in_obsidian/).

I hope this information is helpful. Please let us know if you have any further questions or if there is anything else we can do to assist you.
