### ISSUE TITLE
Bug: Append generated text to the end of the line, not at cursor position

### ISSUE THREAD

**Issue by chrisgrieser** [nhaouari/obsidian-textgenerator-plugin#70]
right now, when the cursor is in the middle of the line and I trigger "generate text", it enters the text right at the cursor position, although it should be appended to the line instead.

(also, and this is mostly minor, when appending, and the last character is not a space, it should add a space, so that you don't always to do that manually.)

**Comment by nhaouari** [comment]
Thank you for reporting the bug. I have fixed the issue in version 0.1.22, where the generated text will now be appended to the line rather than inserting at the cursor position. 

I have also added a feature where a space will be added after the generated text if the last character of the line is not a space.

I appreciate your feedback and apologize for any inconvenience this may have caused. Could you please check the bug in the updated version and let me know if it is working as intended now? 

I would greatly appreciate your help in testing and verifying the fix.

**Comment by chrisgrieser** [comment]
thx! the first issue appears to be fixed. Regarding the second issue, it looks like now the plugin always fills up to two spaces, meaning regardless whether the last character is a space or not, there will be two space before the insertion now
