### ISSUE TITLE
FR: Have Commands with different preset token values

### ISSUE THREAD

**Issue by chrisgrieser** [nhaouari/obsidian-textgenerator-plugin#71]
Exploring the plugin, I found that I frequently switch between two token amounts: 100 tokens for finishing a sentence, and 500 tokens for writing a short paragraph.

Right now, that means frequently using the "change max tokens" command. I think this could be streamlined by being able have commands/hotkeys for each separate token amounts. For example:
- Command 1: Generate Text (with 100 tokens)
- Command 2: generate text (with 500 tokens)

and then I simply have two hotkeys, instead of constantly changing the token amount between the two values.

**Comment by nhaouari** [comment]
Thank you for your suggestion, Chrisgrieser! I'm glad to hear that you've found the plugin useful and that you have an idea for how to make it even more streamlined.

You can use templates to define specific parameters such as the max tokens value. This way, you can create a template with a max tokens value of 100 and another template with a max tokens value of 500, and then simply use the appropriate template whenever you need to generate text with those specific token amounts.

As for hotkeys, I'm happy to let you know that I will be adding the ability to define hotkeys in the templates soon. This will allow you to quickly access your templates and generate text with just a few keystrokes, rather than having to go through the menus to select the template each time.

I hope this helps, and please don't hesitate to let me know if you have any further questions or suggestions!

**Comment by chrisgrieser** [comment]
Thanks! I'll have a look when the hotkeys for templates are released :)

**Comment by nhaouari** [comment]
@chrisgrieser 
I'm pleased to inform you that the hotkeys for templates feature has been developed and will be available in version 0.2.16. Stay tuned for the documentation!

**Comment by nhaouari** [comment]
Check the following  link for the documentation http://text-gen.com/template-file-metadata

**Comment by chrisgrieser** [comment]
thank you, can confirm it is working :)
